- .github/workflows/main.yml
- .github/workflows/publish-registry.yml
It's not possible to set the env using input variables - https://github.com/actions/runner/issues/998
> Hardcode deployment environment

- src/registry.json
> E2E test of Github CI publishing registry

- scripts/verify-registry.ts
- src/registry.json
> Retrigger CI and fix types in verify script

- package.json
- yarn.lock
Bumps `metamask/utils` to `6.0.0`.
> Bump `@metamask/utils` to `6.0.0`

- src/registry.json
Adds MobyMask and Algorand snaps to the allowlist
> Add MobyMask and Algorand to allowlist

- .github/workflows/publish-registry.yml
Fixes the cloudfront invalidation path to hopefully make cache invalidation more consistent.
> Fix cloudfront invalidation path

- src/registry.json
Add latest versions of example snaps to the registry.
> Add latest versions of example snaps

- package.json
- yarn.lock
Bumps `metamask/utils` to `7.1.0`
> Bump `metamask/utils` to `7.1.0`

- src/registry.json
Add new versions of the example snaps to the registry.
> Update example snaps

- src/registry.json
name: Tezos to Tezos Wallet
version: 1.0.0 to 1.0.1
> Tezos snap name and version change

- src/registry.json
Name is just "UniPass"
Version is 0.1.1
> Bump version and name for npm:@unipasswallet/unipass-snap

- src/registry.json
MinaPortal is the final name for this snap
> Change Mina to MinaPortal

- src/registry.json
Arweave snap from 0.2.0 to 0.2.1
> Update Arweave to v0.2.1

- src/registry.json
> Update Blockfence to v0.1.1

- src/registry.json
> Adds Forta snap v0.1.1

- yarn.lock
> deps: semver@6.3.0->6.3.1

- package.json
- yarn.lock
> devDeps: bump @noble/curves, @noble/hashes

- package.json
- yarn.lock
- deps: `@metamask/utils`@`^7.1.0`->`^8.1.0`
- deps(lockfile): `ethereum-cryptography`@`2.0.0`->`2.1.2`
> deps: @metamask/utils@^7.1.0->^8.1.0

- src/registry.json
FYI there are linting errors being thrown now
> Add Solana, Aptos, and Sui snap by Solflare

- src/index.ts
- src/registry.test.ts
The author field was changed to include both a name and website, and the audits array was changed to include the name of the auditor.
> Update author and audits fields

- src/registry.json
Adds Vega Protocol, Masca, Leap Cosmos Wallet, and Web3 Security snaps
Also adds a new version for StarkNet snap
> Even more snaps

- CHANGELOG.md
- package.json
- yarn.lock
This reverts commit a689dc9c80af2619ee475efe53592d3095c674ef (#111).
The release failed in CI and will be rescheduled as-is.
> Revert "2.0.0 (#111)"

- src/registry.json
> Add Partisia Blockchain Snap

- src/registry.json
> Add Rarime

- src/index.ts
- src/registry.json
- src/registry.test.ts
Adds a support struct to the validation schema making it easier to specify multiple types of support links.
> Add support struct

- src/registry.json
> Add cosmos and update rarime

- src/registry.json
> Add connect by drift, update Algorand Wallet and WalletChat

- src/registry.json
All 3 had their names changed, were version bumped to 1.0.3, and were missing metadata
Closes #140 
Closes #141 
Closes #142
> Update Solana Wallet, Aptos Wallet, Sui Wallet

- src/registry.json
Fixes an issue with the formatting on the WalletChat contact email.
> Fix WalletChat email

- src/registry.json
> Update solana and leap

- src/registry.json
> Add ShapeShift Multichain

- .github/workflows/publish-registry.yml
https://octokit.github.io/rest.js/v20#actions-create-workflow-dispatch
> Fix workflow dispatch endpoint

- src/registry.json
This resolves a problem at installation
Closes #154
> Update ShapeShift Multichain

- src/registry.json
> Update Starknet and add CubeSigner

- src/registry.json
This cleans up a lot of metadata for a lot of Snaps. 
Closes #161
> Better metadata

- src/registry.json
> Update website and descriptions for CubeSigner

- src/registry.json
> Add website and correct descriptions for Vega

- src/registry.json
The website is ready for the Snap!
> Add website and better description for ShapeShift Multichain

- src/registry.json
> Add leap Cosmos and fix Mystic Labs Cosmos

- src/registry.json
> Correct author and website for MinaPortal

- src/registry.json
> Correct Cosmos Extension version 0.1.14

- src/registry.json
> Update partisia website and forta version

- src/registry.json
Fixes the Forta version, removing an unintentional whitespace.
> Fix Forta version

- src/registry.json
> Add Web3MQ and update Rarime

- src/registry.json
> Update Cosmos extension and metadata for ShapeShift and Saferoot

- src/registry.json
> Update Tenderly TX Preview version and metadata for Assets Risk Detection

- src/registry.json
> Update Kleros Scout and metadata for RariMe and Vega

- src/registry.json
> Add v0.1.1 of MinaPortal

- src/registry.json
This rolls back to 1.1.0 and closes #192
> Remove Kleros Scout 1.2.0

- src/registry.json
> Update Cosmos Extension

- src/registry.json
> Update Wallet Guard

- src/registry.json
> Update threat intel

- src/registry.json
> Add Polkadot Wallet v 0.7.7

- src/index.ts
- src/registry.json
This adds a hidden field to the registry, which we can use for the example Snaps.
> Add hidden field to metadata

- src/registry.json
Adds Filsnap v1.0.1 and Sui v1.0.1 to the registry.
Also adds website and FAQ for Polkadot Wallet
This closes #221 and #223
> Add Filsnap v1.0.1 and Sui v1.0.1

- src/registry.json
This closes #231
This closes #230
> Update Wallet Guard and Vega

- src/registry.json
This closes #237 
This closes #239
> Update filecoin wallet description and update RariMe

- src/registry.json
Updates the keyring example snap.
> Update keyring example snap

- src/registry.json
> Update RariMe 0.7.2

- src/registry.json
> Update RariMe to 0.8.0

- src/registry.json
> Update Casper to 1.0.4

- src/registry.json
> Update Leap Cosmos Wallet to 0.1.17

- src/registry.json
> Update Push 1.1.2

- src/registry.json
This PR adds one new example snap (get-file-example-snap) and adds the newest versions of the rest of the example snaps.
> Add new versions of example snaps

- src/registry.json
This updates short and long description for WalletChat
> Update metadata for WalletChat

- src/registry.json
- yarn.lock
> Add QuickIntel v1.0.1

- src/registry.json
- yarn.lock
This closes #273 
This closes #274
> Remove Sui Wallet and Aptos Wallet

- src/registry.json
> Add Astar Wallet

- src/registry.json
> Add Nocturne

- src/registry.json
This closes #266
Also updates Audit Report URL for Nocturne
> Add Web3 Antivirus

- src/registry.json
> Update Polkadot and RariMe

- src/registry.json
> Update Nocturne and RariMe

- src/index.ts
- src/registry.test.ts
Add a handful of new metadata fields that are needed in the near future.
> Add more metadata fields

- src/registry.json
This adds the Snap without a category so the team can test it before making it visible in the directory.
Closes #310
> Add Hedera Wallet

- src/registry.json
This closes #324
This closes #326
> Update Leap Cosmos Wallet and Mina Portal

- src/registry.json
This closes #331 
This closes #329
> Update Sign in with XMTP and add RSS3 Social Notifier

- src/registry.json
> Re-enable Drift

- src/registry.json
The companion dapp now supports mainnet for the Snap so users can connect from the main URL
> Update website for Astar

- src/registry.json
This closes #332
This closes #339
> Add Dedaub and TM ChainSafer

- src/registry.json
Changes to add a new version of the SSK to the registry
- [Snap manifest](https://github.com/MetaMask/snap-simple-keyring/blob/main/packages/snap/snap.manifest.json)
> chore: add SSK version 1.1.1

- src/registry.json
This closes #348
This closes #330
> Update id for ChainSafer and add AMAX UP

- src/registry.json
This closes #355 
This closes #347
> Update Near and Push

- src/registry.json
Adds 1 sentence to the description
> Update RariMe description

- src/registry.json
> Update starknet 2.4.0

- src/registry.json
Adds category and website, and updates developer info
> Update Metadata for Hedera

- src/registry.json
The previous URL was incorrect
> Update Hedera Wallet KB URL

- src/registry.json
> Update Hedera Wallet Discord URL

- src/registry.json
> Add Galactica ZK Vault

- src/registry.json
Version is 0.0.2
(This will be invalid because the icon is missing, will follow up in another commit)
Closes #377
> Add Web3 Ticketing

- src/index.ts
Adds terms of use as allowed metadata.
Progresses https://github.com/MetaMask/snaps/issues/2046
> Add terms of use to metadata

- src/registry.json
> Update metadata for Web3 Antivirus

- src/registry.json
> Add EAS and update MetaMask Support

- src/registry.json
This closes #396
This closes #397
> Hide Nocturne and EAS

- src/index.ts
- src/registry.test.ts
Tweak additional source code schema, changing it from a string array to an array of objects.
> Tweak additional source code schema

- src/registry.json
This closes #407
This closes #410
> Update RariMe and Hedera Wallet

- src/registry.json
Replace 2.0.1 with 2.0.2
This closes #416
> Update Rarime to 2.0.2

- src/registry.json
Replace 0.1.5 with 0.2.4
This closes #418
> Update hedera-wallet-snap to 0.2.4

- src/registry.json
Replace 2.0.2 with 2.0.3
This closes #422
> Update Rarime to 2.0.3

- src/registry.json
Increment versions of cronjob and wasm example snaps
> Increment versions of cronjob and wasm example snaps

- src/registry.json
> Update Silent Shard: Removing hidden toggle and adding back category

- src/registry.json
> Update Capsule logo and FAQ

- src/registry.json
> Remove saferoot, Update vega, Update xmtp

- src/registry.json
> Updating Silent Shard short description

- src/registry.json
> Updating Safeheron Multi Party Sig CPP link

- src/registry.json
This adds the newest versions of the example snaps.
> Increment example versions

- src/registry.json
> Update Starknet to 2.5.2

- src/registry.json
This adds `@metamask/home-page-example-snap` to the registry.
> Add home page example Snap

- src/registry.json
> Update Partisia Blockchain

- src/registry.json
> Add category property to the Rubic Snap.

- src/registry.json
> New Snap Hapi

- src/registry.json
> Silent Shard Snap update

- src/registry.json
> Update MetaMask Support

- src/registry.json
This 
Closes #528 
Closes #529
> Update Masca, Rarime

- src/registry.json
> Remove TM ChainSafer

- src/registry.json
> Update Linea Voyager

- src/registry.json
> Update Starknet Snap

- src/registry.json
> Update example snaps versions

- src/registry.json
this adds the images-example-snap to the registry.
> Add images example snap

- src/registry.json
> New Snap Xtremely

- src/registry.json
> Restore prev versions of Vega

- src/registry.json
> Update Silent Shard

- src/registry.json
> Update MetaMask Support snap

- src/registry.json
Add the Interactive UI example snap to the allowlist.
> Add interactive ui example snap

- scripts/verify-snaps.ts
- src/registry.json
Since we are fetching the entire Snap we can compute the checksum and check it against the reported one for additional safety.
> ci: verify checksums

- src/registry.json
> Update hashDit Security

- src/registry.json
Bumps the interactive UI example Snap.
> Bump interactive UI example

- src/registry.json
> Update filecoin wallet

- src/registry.json
> Update Hedera Wallet

- src/registry.json
> Update Starknet 2.9.0

- src/registry.json
> Update Cardano Wallet Snap

- src/registry.json
Add name lookup example Snap to the registry for E2E.
> Add name lookup example Snap

- src/registry.json
> Update Desc for LineaVoyager

- src/registry.json
Updates the JSX example Snap to run it in E2E.
> Update JSX example Snap

- src/registry.json
Delist Zion from the directory as their accompanying dapp is currently having problems preventing users from sending BTC.
> Delist Zion

- src/registry.json
> New Aeternity Wallet

- src/registry.json
I forgot to update this in #782.
> Update example localization Snap

- src/registry.json
I managed to miss more example Snaps somehow, so here's the remaining bunch (hopefully).
> Bump more examples

- src/registry.json
Updating Mendi Snap category from `transaction insights` to `notifications`
> Update Mendi snap Category

- src/registry.json
> Update Social Names

- src/registry.json
Delist Clusters and SocialName snaps until NameRes issue fixed.
> Delist Clusters and SocialName snaps until NameRes issue fixed.

- src/registry.json
> Add disclaimers for FIO and Unstoppable

- src/registry.json
> Add Web3 Address Book

- src/registry.json
Kadena requested to hold off on allowListing their Snap until they are ready.
> Delisting until kadena gives the greenlight.

- src/registry.json
> Update D3 Connect

- src/registry.json
> Update Identify 

- src/registry.json
> New Hns.id

- src/registry.json
> Update HNS.id add category

- src/registry.json
> Update Qtum metadata

- src/registry.json
Bump notification example Snap for E2E tests.
> Bump notification example Snap

- src/registry.json
> Unlist Polkadot

- src/registry.json
> Update Aleo Metadata

- src/registry.json
> New SelfNameResolution

- src/registry.json
> New XDCWeb3Domains

- src/registry.json
> Update Self Name Resolution

- src/registry.json
> New XRP Name

- package.json
- yarn.lock
This bumps `@metamask/utils` from `^10.0.0` to `^11.0.1`.
> Bump `@metamask/utils` from `^10.0.0` to `^11.0.1`

- src/registry.json
Add newest example Snaps to registry for E2E.
> Bump example Snaps

- src/registry.json
Builder requested to change the Dev Name
> Change Dev name per Builder request

- src/registry.json
Req from builder to update their Snap Desc.
The content was provided via TG.
> Update Snap Dec

- src/registry.json
> New SafeTransfer

- src/registry.json
> Update Beranames Resolver

- src/registry.json
We will use `npm:@metamask/webpack-plugin-example-snap` for end-to-end testing in the extension.
> Add `npm:@metamask/webpack-plugin-example-snap`

- src/registry.json
> Update: downgrade ShapeShift

- src/registry.json
> Unlist MetaMask support snap

- src/registry.json
> New 0xNameResolver

- src/registry.json
> Update Casper Manager

- .github/workflows/publish-registry.yml
In #1118 I missed a couple instances.
> Update more workflows to use `MetaMask/action-checkout-and-setup`

- src/registry.json
Bump interactive UI example Snap to latest.
> Bump interactive UI example Snap

- src/registry.json
Bump WASM example snap to latest.
> Bump WASM example Snap

- src/registry.json
> Update Qubic Wallet Description

- src/registry.json
> Update Boba Network

- src/registry.json
Add the Protocol Example Snap to the registry for E2E purposes.
> Add Protocol Example Snap

- src/registry.json
> feat: change ZNS Connect name

- package.json
- tsconfig.json
- yarn.lock
Combining a bunch of the pending Dependabot PRs into one.
> chore: Bump MetaMask dependencies

- src/registry.json
No code change in Snap. Just adding their Website to the Registry.
> Adding Website for Celestial

- src/registry.json
No Snap code changes only updating their Links
> Update Celestial links.

- src/registry.json
> Upgrade celestials snap to 1.1.0

- src/registry.json
> Upgrade conft Domains to 0.3.7

- src/registry.json
> Update Avail Snap

- src/registry.json
> feat: new snap - quai wallet

- src/registry.json
> chore: update Snap Safetransfer version to 1.0.8

- src/registry.json
> Update Quai Wallet

- src/registry.json
> Add UTU Trust

- src/registry.json
> Add know your transaction

- src/registry.json
> Block Wallet Guard

- src/registry.json
> Update Conft Domains
