src/index.ts
This adds a `name` property to verified Snaps, for displaying in the UI upon installation.
Related to: MetaMask/MetaMask-planning#298.
=> Add name property to verified snaps

.github/workflows/main.yml, .github/workflows/publish-registry.yml
What is the current state of things and why does it need to change?
Artifacts are published to gh-pages
What is the solution your changes offer and how does it work?
Deploy registry files to remote storage and creates CF invalidation right after it.
aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef action has to be whitelisted
See: API-226
=> API-226: update action for pushing registry artifacts to remote storage

scripts/sign-registry.ts, scripts/verify-registry.ts, src/registry.json
.env was set, used for other envs, which blocked private key from being used.
Also updated registry.json to trigger CI
=> Fix private key trying to be loaded from path before env first.

scripts/verify-registry.ts
This pull request refactors the `assertHexString` function to use the `isStrictHexString` function provided by the
`@metamask/utils` package.
In the previous implementation, the `assertHexString` function was used to assert that a given string is a valid
hexadecimal string. However, the same functionality is already provided by the `isStrictHexString` function provided
by the `@metamask/utils` package.
Therefore, we have removed the `assertHexString` function and replaced all its occurrences with calls to `isStrictHexString`.
1. Replace `assertHexString` function with calls to `isStrictHexString`.
=> Refactor assertHexString function to use isStrictHexString

src/registry.json
Fixes a mistake in the BIP-32 example checksum.
Also adds some older versions that are used in testing.
=> Fix BIP-32 example checksums

.github/workflows/publish-registry.yml
Now we create an invalidation for both CloudFront distributions.
`AWS_CF_SECONDARY_DISTRIBUTION_ID` will need to be added.
=> Create invalidation for secondary CloudFront distribution after deployment

src/index.ts, src/registry.test.ts
The added metadata will be visible to users when they're adding a new snap account. All the newly introduced fields are optional, as they might not be necessary for other types of snaps.
Closes: MetaMask/accounts-planning/issues/21
=> Add new snap metadata

src/registry.json
Two snaps were missing the `npm:` prefix.
=> Add missing npm: prefix

src/index.ts
Validate snap ids, checking that they are prefixed with `npm:`.
=> Validate snap ids

src/index.ts, src/registry.test.ts
This adds a new category field to the metadata, which can be set to one of the three categories at launch.
=> Add category enum to metadata

.github/workflows/main.yml, .github/workflows/publish-registry.yml, .github/workflows/publish-release.yml
Rather than tagging NPM publishers, we now tag Snaps publishers. Messages will be sent in the `metamask-snaps` channel.
=> Tag Snaps publishers for releases

.github/workflows/main.yml, .github/workflows/publish-registry.yml
The directory fetches from the registry. To ensure it's always up-to-date, we can automatically call the workflow to update the directory after the registry is deployed.
=> Republish directory after registry deployment

src/registry.json
Non-vanity Discord links are unsafe, as they can be claimed by other people. Discord channel links don't work, since they are not invites.
=> Remove unsafe or broken Discord links

.github/workflows/build-lint-test.yml
Node.js v19 is currently failing to download.
=> Use Node.js v20 instead of v19 in CI

src/registry.json
This temporarily removes some websites that do not yet support the associated Snap. 
They will be added again when they are ready.
=> Remove websites for 4 Snaps

src/registry.json
This removes the Starknet snap temporarily, until it is updated.
=> Temporarily remove Starknet snap

scripts/verify-snaps.ts
This PR re-enables the "verify snaps" script, which was previously disabled in #80.
=> Enable verify snaps script

src/registry.json
bumps network access example snap version to 0.38.2-flask.1
=> Bump metamask/networkacess-example-snap version

src/registry.json
Adds the keyring example snap to the registry. This is used for E2E testing and is hidden from the directory.
=> Add keyring example snap

src/registry.json
Fixes the contact email for Filecoin Wallet to be `mailto:filecoin-snap@fil.org`
=> Correct Filecoin contact email

src/registry.json
This PR adds a new version of Masca Snap (v1.1.0).
Changes in the new version can be found here: https://hackmd.io/eOilSHWdS7uylpdHBkxN3A
=> Update Masca 1.1.0

src/registry.json
This assigns Quick Intel to the correct category Transaction Insights
=> Put QuickIntel in correct category

src/registry.json
This adds the 2.1.0 versions of the example snaps - plus 2.2.0 of manage state, and 1.1.0 of localization.
=> Add new version shasums of example snaps

src/registry.json
This updates the get-file example snap to 1.1.0
=> Update get-file example snap version

package.json, scripts/create-key.ts, scripts/verify-registry.ts, src/verify.test.ts, src/verify.ts, yarn.lock
Use `noble-hashes` for SHA256 instead of the utility function from `@noble/secp256k1` since the existing code is not compatible with React Native. Use `noble-curves` as that still supports CommonJS.
=> Use `noble-hashes` and `noble-curves`

src/index.ts, src/registry.test.ts
Add `keyRecovery` field to the metadata schema. To be used by account management snaps.
=> Add key recovery field

src/index.ts, src/registry.test.ts
Adds a metadata field for additional source code. This can be used for open source parts of the snap that are in addition to the main snap source code.
Fixes https://github.com/MetaMask/snaps-registry/issues/395
=> Add additional source code field

src/registry.json
The lookup example snap was prematurely added to the allowlist and is causing build errors in the directory.
This snap can be re-added once the name lookup API is stable and requires allowlisting.
=> Remove lookup example snap from allowlist

src/registry.json
=> Add Safeheron

src/registry.json
This reverts commit c65e1506563c69bd694509ef42b1a0e5c98def35.
=> Revert "Update Starknet to 2.5.2 (#469)"

src/verify.test.ts, src/verify.ts
The `signature` field can have a variable length depending on leading zeroes in the raw bytes.
=> Fix registry validation

src/registry.json
See #468. This redoes #469 after having to revert it.
=> Bump `@consensys/starknet-snap` to `2.5.2`

src/registry.json
This reverts commit 4712b37636987cb05739973c8e04f497106fa900.
=> Revert "Bump `@consensys/starknet-snap` to `2.5.2` (#474)"

src/registry.json
This closes:
#480 
#481 
#482 
#483 
#484 
#457 
**Note:** Rubic Snap builder doesnt want the Snap to be displayed in Directory, so I did not add the `category` property for it.
=> polkagate-rubic-hedera-alephzero-safeheron-defiarmor

package.json, scripts/verify-snaps.ts, src/index.ts, src/registry.test.ts, yarn.lock
This adds support for a screenshots field in the registry. Snaps may have three screenshots, with a size of 960x540. Screenshots should be placed in `src/images/<snapId>`, i.e., `src/images/@organisation/snap-name`, and should be named `1.png`, `2.png`, `3.png` (or `.jpe?g`). They can then be added to the registry by adding `screenshots` to the metadata, with the path to each file as array items.
```json
{
"verifiedSnaps": {
"npm:@organisation/snap-name": {
"metadata": {
"screenshots": [
"./images/@organisation/snap-name/1.png",
"./images/@organisation/snap-name/2.png",
"./images/@organisation/snap-name/3.png"
]
}
}
}
}
```
=> Add screenshots field

src/registry.json
Changing the `category` of the Tezoro Snap as it aligns more with `Security` than with `Interoperability`.
=> Change in "category".

package.json, yarn.lock
- See https://github.com/MetaMask/snaps/pull/2445
- See https://github.com/MetaMask/core/pull/3645
=> Bump `@metamask/superstruct` to `^3.1.0`, `@metamask/utils` to `^9.0.0`

src/registry.json
Update starknet snap, add legacy 2.7.0 in allowlist
=> Update Starknet: add legacy version 2.7.0

package.json, yarn.lock
Bumps MetaMask dependencies to their latest version, clearing out Dependabot PRs.
=> chore: Bump MetaMask dependencies

.github/workflows/publish-registry.yml, .github/workflows/publish-release.yml
This updates the publish workflows to send a Slack message in `metamask-snaps-deployments`.
=> Use `metamask-snaps-deployments` channel for deployment messages

src/registry.json
We need to whitelist the new v1.1.6 which now uses packages from the new [accounts monorepo](https://github.com/MetaMask/accounts) and we'd like to use this one in extension E2E tests.
Thanks!
=> Update SSK versions

src/registry.json
The contact fields for some snaps in the `registry.json` file currently contain email addresses without the `mailto:` prefix. This could cause inconsistencies or issues where the correct format (with `mailto:`) is expected.
This PR updates the `contact` field for the affected snaps to include the `mailto:` prefix, ensuring all email addresses are in the proper format for links and interactions. Specifically, three snaps have been updated:
- **Qtum Snap**: Changed `"support@qtum.info"` to `"mailto:support@qtum.info"`.
- **Aeternity Snap**: Changed `"donna@aeternity.com"` to `"mailto:donna@aeternity.com"`.
- **TokenScript Snap**: Changed `"v@smarttokenlabs.com"` to `"mailto:v@smarttokenlabs.com"`.
No related issues were filed, but these changes are necessary for consistent contact …
=> Update missing mailto: in some snaps contact metadata

src/registry.json
=> New EOS Wallet

src/registry.json
This updates the following example Snaps:
- `npm:@metamask/bip32-example-snap` to `2.3.0`.
- `npm:@metamask/bip44-example-snap` to `2.2.0`.
- `npm:@metamask/get-entropy-example-snap` to `2.2.0`.
- New: `npm:@metamask/preferences-example-snap` to `1.0.0`.
=> Update example Snaps

src/registry.json
This adds version 2.3.0 of the lifecycle hooks example to the registry.
=> chore: Bump lifecycle hooks example

src/registry.json
This closes #1296 
The developer published the Snap to npm incorrectly, so this is pending a fix.
=> Add Wise Signer

src/registry.json
Context:
The update to 2.0.0 doesn't change anything on the snap-simple-keyring. It's a major update, because we have made the snap-simple-keyring-site publishable, in order to use it in our e2e as a local server.
See more here:
- https://github.com/MetaMask/snap-simple-keyring/pull/163
- https://github.com/MetaMask/metamask-extension/pull/36557
=> Add `snap-simple-keyring` v2.0.0 to the allowlist
